### ISSUE TITLE
DataSource should have a "name" Property

### ISSUE THREAD

**Issue by seifertm** [eseifert/gral#70]
When creating a DataTable, it should be possible to specify a name that is e.g. displayed in the legend of a plot.

## Current behaviour
Currently, when creating an XYPlot from a DataTable, the Legend displays "de.erichseifert.gral.DataTable@<hashCode>" as a name. The only way to change it is to create a DataSeries (which takes a name argument) from the newly created DataTable.

## Expected behaviour
DataTable should have a name property.

 _Imported from trac ticket #71,  created by mseifert on 12-13-2013 at 12:30, last modified: 01-20-2014 at 16:15_

**Comment by seifertm** [comment]
The concept should be extended in that every `DataSource` should have a "name" property.

**Comment by seifertm** [comment]
Done with commit 2a08a1a1441dd605e8b676dd0b2f112220479040.

**Comment by saviola777** [comment]
The legend problem remains, since DataTable does not override `toString`, so the name is not used for the legend label. Since the `getName` method is available in the DataSource interface, it could be used to generate the label instead of `toString`.
